import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    ar: {
        "sidebar.title": "إدارة سيتي أوردرز",
        "sidebar.dashboard": "لوحة التحكم",
        "sidebar.merchant_approvals": "موافقات التجار",
        "sidebar.subscription_plans": "خطط الاشتراك",
        "sidebar.subscriptions": "الاشتراكات",
        "sidebar.payment_requests": "طلبات الدفع",
        "sidebar.audit_log": "سجل التدقيق",
        "sidebar.payment_methods": "طرق الدفع",
        "sidebar.categories": "الأقسام الرئيسية",
        "sidebar.staff": "فريق الإدارة",
        "sidebar.roles_permissions": "صلاحيات الأدوار",
        "sidebar.promos": "أكواد الخصم",
        "sidebar.announcements": "الإعلانات العامة",
        "sidebar.settings": "الإعدادات",
        "sidebar.security": "الأمان",
        "sidebar.chats": "المحادثات",
        "sidebar.delivery_network": "شبكة التوصيل",
        "sidebar.delivery_agents": "الطيارين والمديونيات",
        "sidebar.delivery_plans": "خطط تحصيل الطيارين",
        "sidebar.delivery_payment_requests": "طلبات دفع الطيارين",
        "sidebar.logout": "تسجيل الخروج",
        // Login
        "login.title": "إدارة سيتي أوردرز",
        "login.email": "البريد الإلكتروني",
        "login.password": "كلمة المرور",
        "login.submit": "تسجيل الدخول",
        "login.loading": "جاري الدخول...",
        "login.accessDenied": "الدخول مرفوض. يجب استخدام حساب مدير.",
        "login.success": "تم تسجيل الدخول بنجاح",
        "login.error": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
        // Global Settings
        "settings.title": "الإعدادات العامة",
        "settings.subtitle": "تهيئة المعايير العامة للتجار والمشروع.",
        "settings.free_trial": "تفعيل الفترة التجريبية",
        "settings.free_trial_desc": "السماح للتجار الجدد ببدء تجربة مجانية دون دفع.",
        "settings.trial_days": "أيام الفترة التجريبية",
        "settings.grace_days": "فترة السماح (أيام)",
        "settings.max_offers": "أقصى عدد من العروض (التجريبية)",
        "settings.save": "حفظ الإعدادات",
        "settings.saving": "جاري الحفظ...",
        "settings.success": "تم تحديث الإعدادات بنجاح",
        "settings.error": "فشل تحديث الإعدادات",
        "settings.security": "الأمان",
        "settings.change_password": "تحديث كلمة مرور حساب الإدارة",
        "settings.current_password": "كلمة المرور الحالية",
        "settings.new_password": "كلمة المرور الجديدة",
        "settings.confirm_password": "تأكيد كلمة المرور الجديدة",
        "settings.update_password": "تغيير كلمة المرور",
        "settings.updating": "جاري التحديث...",
        "settings.loading": "جاري تحميل الإعدادات...",
        "settings.connectionError": "خطأ في الاتصال",
        "settings.connectionErrorDesc": "فشل تحميل الإعدادات من الخلفية. تأكد أن الباك يعمل على",
        "settings.settingsUpdated": "تم تحديث الإعدادات بنجاح",
        "settings.settingsUpdateFailed": "فشل تحديث الإعدادات",
        "settings.passwordChanged": "تم تغيير كلمة المرور بنجاح",
        "settings.passwordChangeFailed": "فشل تغيير كلمة المرور",
        "settings.passwordMismatch": "كلمتا المرور غير متطابقتان",
        "settings.passwordTooShort": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
        
        // Dashboard
        "dashboard.title": "لوحة التحكم",
        "dashboard.subtitle": "متابعة الطلبات، الإيرادات، والتجار من مكان واحد.",
        "dashboard.stats.total_orders": "إجمالي الطلبات",
        "dashboard.stats.active_orders": "{count} طلب نشط",
        "dashboard.stats.late_orders": "طلبات متأخرة",
        "dashboard.stats.late_desc": "نشطة منذ أكثر من 30 دقيقة",
        "dashboard.stats.delivered_revenue": "إيراد الطلبات المسلمة",
        "dashboard.stats.today_revenue": "اليوم: {amount}",
        "dashboard.stats.customers": "العملاء",
        "dashboard.stats.new_customers": "{count} عملاء جدد خلال 7 أيام",
        "dashboard.stats.merchants": "التجار",
        "dashboard.stats.online_merchants": "{count} فاتحين الآن",
        "dashboard.stats.temp_closed": "متاجر مغلقة مؤقتا",
        "dashboard.stats.hidden_merchants": "مخفية عن العملاء",
        "dashboard.stats.pending_approvals": "طلبات موافقة",
        "dashboard.stats.pending_payments": "طلبات دفع معلقة",
        "dashboard.stats.unread_chats": "رسائل غير مقروءة",
        "dashboard.stats.open_chats": "{count} محادثة مفتوحة",
        "dashboard.stats.payment_methods": "طرق الدفع",
        "dashboard.stats.free_trial": "التجربة المجانية",
        "dashboard.stats.enabled": "مفعلة",
        "dashboard.stats.disabled": "متوقفة",
        "dashboard.recent_orders": "آخر الطلبات",
        "dashboard.recent_orders_desc": "أحدث 6 طلبات",
        "dashboard.no_recent_orders": "لا توجد طلبات حديثة",
        "dashboard.attention_orders": "طلبات تحتاج متابعة",
        "dashboard.attention_orders_desc": "أقدم طلبات نشطة",
        "dashboard.no_attention_orders": "لا توجد طلبات متأخرة حاليا",
        "dashboard.system_health": "حالة النظام",
        "dashboard.api_status": "واجهة البرمجة",
        "dashboard.api_online": "تعمل",
        "dashboard.api_offline": "متوقفة",
        "dashboard.latency": "زمن الاستجابة",
        "dashboard.last_checked": "آخر فحص",
        "dashboard.retry": "إعادة المحاولة",
        "dashboard.server_error_title": "تعذر الاتصال بالخادم",
        "dashboard.server_error_desc": "تأكد أن الباك يعمل على المنفذ 5014 ثم أعد المحاولة.",
        "dashboard.reconnect": "إعادة الاتصال",
        "dashboard.currency": "جنيه",
        "dashboard.order_status.pending": "قيد الانتظار",
        "dashboard.order_status.accepted": "مقبول",
        "dashboard.order_status.preparing": "جاري التجهيز",
        "dashboard.order_status.outfordelivery": "خرج للتوصيل",
        "dashboard.order_status.delivered": "تم التوصيل",
        "dashboard.order_status.cancelled": "ملغي",
        "dashboard.time.now": "الآن",
        "dashboard.time.minutes_ago": "منذ {count} دقيقة",
        "dashboard.time.hours_ago": "منذ {count} ساعة",
        "dashboard.time.recent": "حديثا",

        // Chats
        "chats.title": "المحادثات",
        "chats.subtitle": "تواصل مباشر بين الإدارة والتجار.",
        "chats.start_chat": "ابدأ محادثة مع تاجر",
        "chats.search_placeholder": "ابحث عن تاجر...",
        "chats.loading": "جاري التحميل...",
        "chats.no_merchants": "لا يوجد تجار.",
        "chats.current_chats": "المحادثات الحالية",
        "chats.no_chats": "لا توجد محادثات بعد.",
        "chats.loading_messages": "جاري تحميل الرسائل...",
        "chats.no_messages_title": "لا توجد رسائل بعد",
        "chats.no_messages_desc": "اكتب أول رسالة للتاجر.",
        "chats.attachment_title": "إرفاق صورة",
        "chats.message_placeholder": "اكتب رسالة...",
        "chats.send": "إرسال",
        "chats.select_chat_title": "اختر محادثة",
        "chats.select_chat_desc": "ابدأ من تاجر أو افتح محادثة موجودة.",
        "chats.read": "تمت القراءة",
        "chats.sent": "تم الإرسال",
        "chats.upload_failed": "فشل رفع الصورة.",

        // Payment Methods
        "payments.title": "طرق الدفع",
        "payments.subtitle": "إدارة الطرق التي يستخدمها التجار لدفع الاشتراكات.",
        "payments.add": "إضافة طريقة دفع",
        "payments.edit": "تعديل طريقة الدفع",
        "payments.displayName": "الاسم المعروض",
        "payments.receiver": "المستلم",
        "payments.receiverName": "اسم المستلم",
        "payments.receiverNumber": "رقم المستلم",
        "payments.instructions": "التعليمات",
        "payments.sortOrder": "ترتيب الفرز",
        "payments.status": "الحالة",
        "payments.actions": "الإجراءات",
        "payments.isActive": "نشط",
        "payments.active": "نشط",
        "payments.inactive": "غير نشط",
        "payments.confirmDelete": "هل أنت متأكد من رغبتك في حذف طريقة الدفع هذه؟",
        "payments.success.create": "تم إنشاء طريقة الدفع بنجاح",
        "payments.success.update": "تم تحديث طريقة الدفع بنجاح",
        "payments.success.toggle": "تم تبديل الحالة بنجاح",
        "payments.success.delete": "تم حذف طريقة الدفع بنجاح",
        "payments.error.delete": "فشل حذف طريقة الدفع",
        "payments.loading": "جاري تحميل طرق الدفع...",
        "payments.cancel": "إلغاء",
        "payments.save": "حفظ",

        // Categories
        "categories.title": "الأقسام الرئيسية",
        "categories.subtitle": "إدارة الأقسام العامة للأغذية والمنتجات والرسوم التعبيرية الخاصة بها.",
        "categories.add": "إضافة قسم",
        "categories.edit": "تعديل قسم",
        "categories.icon": "الأيقونة",
        "categories.nameSlug": "الاسم / الرابط المعرف",
        "categories.name": "الاسم",
        "categories.slug": "الرابط المعرف",
        "categories.description": "الوصف",
        "categories.image": "الصورة",
        "categories.sortOrder": "ترتيب الفرز",
        "categories.status": "الحالة",
        "categories.actions": "الإجراءات",
        "categories.active": "نشط",
        "categories.inactive": "غير نشط",
        "categories.search": "البحث في الأقسام...",
        "categories.showInactive": "عرض غير النشط",
        "categories.sortByOrder": "ترتيب حسب الفرز",
        "categories.sortByName": "ترتيب حسب الاسم",
        "categories.saveOrder": "حفظ الترتيب",
        "categories.confirmDelete": "هل أنت متأكد من رغبتك في حذف القسم \"{name}\"؟ سيؤدي ذلك أيضاً إلى إزالته من أي علامات تجارية مرتبطة به.",
        "categories.loading": "جاري تحميل الأقسام...",
        "categories.noCategories": "لم يتم العثور على أقسام.",
        "categories.nameRequired": "الاسم مطلوب",
        "categories.allowedImages": "المسموح به: jpg, png, webp. بحد أقصى 5 ميجا بايت.",
        "categories.cancel": "إلغاء",
        "categories.save": "حفظ",
        "categories.noImg": "لا توجد صورة",

        // Staff
        "staff.title": "فريق الإدارة",
        "staff.subtitle": "إدارة المسؤولين عن المنصة والتحكم بالصلاحيات.",
        "staff.add": "إضافة عضو فريق",
        "staff.search": "البحث عن موظف...",
        "staff.total": "الإجمالي: {count} موظفين",
        "staff.assignedRole": "الدور المعين",
        "staff.newStaff": "عضو فريق جديد",
        "staff.fullName": "الاسم الكامل",
        "staff.email": "البريد الإلكتروني",
        "staff.password": "كلمة المرور",
        "staff.adminAccess": "صلاحية المسؤول",
        "staff.adminAccessDesc": "سيتم منح هذا المستخدم حق الوصول الكامل غير المقيد لكامل لوحة التحكم والإدارة.",
        "staff.createBtn": "إنشاء عضو فريق",
        "staff.confirmDelete": "هل تريد حذف {name}؟",
        "staff.success.create": "تم إنشاء المستخدم بنجاح",
        "staff.success.delete": "تم حذف المستخدم بنجاح",
        "staff.error.create": "فشل إنشاء المستخدم",
        "staff.error.delete": "فشل حذف المستخدم",
        "staff.loading": "جاري تحميل فريق الإدارة...",
        "staff.superAdmin": "مدير عام",
        "staff.status": "الحالة",
        "staff.active": "نشط",
        "staff.inactive": "غير نشط",
        "staff.confirmToggle": "هل أنت متأكد من تغيير حالة حساب {name}؟",
        "staff.success.toggleStatus": "تم تبديل حالة الحساب بنجاح",
        "staff.error.toggleStatus": "فشل تعديل حالة الحساب",
        "staff.resetPassword": "إعادة تعيين كلمة المرور",
        "staff.enterNewPassword": "أدخل كلمة المرور الجديدة (6 أحرف على الأقل)",
        "staff.success.resetPassword": "تمت إعادة تعيين كلمة المرور بنجاح",
        "staff.error.resetPassword": "فشل إعادة تعيين كلمة المرور",

        // Roles & Permissions
        "roles.title": "صلاحيات الأدوار",
        "roles.subtitle": "تهيئة صلاحيات الوصول والتحكم لموظفي الإدارة",
        "roles.create": "إنشاء دور مخصص",
        "roles.systemRoles": "أدوار النظام",
        "roles.customRoles": "أدوار مخصصة",
        "roles.noCustomRoles": "لم يتم إنشاء أدوار مخصصة بعد.",
        "roles.roleNamePlaceholder": "اسم الدور (مثال: الدعم الفني)",
        "roles.systemRoleLabel": "دور النظام - وصول كامل",
        "roles.editBtn": "تعديل الصلاحيات",
        "roles.save": "حفظ الصلاحيات",
        "roles.cancel": "إلغاء",
        "roles.confirmDelete": "هل أنت متأكد من رغبتك في حذف هذا الدور؟",
        "roles.systemRoleInfoTitle": "دور النظام الأساسي",
        "roles.systemRoleInfoDesc": "أدوار النظام لديها سلوكيات محددة مسبقاً داخل النظام ولا يمكن تعديل نقاط الوصول الخاصة بها هنا.",
        "roles.endpointsTotal": "{selected} / {total}",
        "roles.selectRolePlaceholder": "اختر دوراً لعرض أو تعديل الصلاحيات",
        "roles.success.create": "تم إنشاء الدور بنجاح",
        "roles.success.update": "تم تحديث الدور بنجاح",
        "roles.success.delete": "تم حذف الدور",
        "roles.error.create": "فشل إنشاء الدور",
        "roles.error.update": "فشل تحديث الدور",
        "roles.error.delete": "فشل حذف الدور",
        "roles.loading": "جاري تحميل الأدوار...",

        // Promo Codes
        "promos.title": "أكواد الخصم",
        "promos.subtitle": "متابعة جميع أكواد الخصم النشطة عبر المنصة",
        "promos.search": "البحث بالكود أو اسم المتجر...",
        "promos.noPromos": "لم يتم العثور على أكواد خصم",
        "promos.noPromosDesc": "حاول تغيير كلمة البحث أو التصفية.",
        "promos.discount": "الخصم",
        "promos.usages": "الاستخدامات",
        "promos.minOrder": "الحد الأدنى للطلب",
        "promos.starts": "يبدأ:",
        "promos.expires": "ينتهي:",
        "promos.neverExpires": "لا ينتهي أبداً",
        "promos.unlimited": "غير محدود",
        "promos.loading": "جاري تحميل أكواد الخصم...",
        "promos.by": "بواسطة {brand}",
        "promos.maxDiscount": "(الحد الأقصى {amount} جنيه)",
        "promos.status.all": "الكل",
        "promos.status.active": "نشط",
        "promos.status.scheduled": "مجدول",
        "promos.status.expired": "منتهي",
        "promos.status.usedup": "مستهلك بالكامل",
        "promos.status.disabled": "معطل",

        // Announcements
        "announcements.title": "الإعلانات العامة والبث",
        "announcements.subtitle": "بث الرسائل والإعلانات لجميع مستخدمي المنصة.",
        "announcements.new": "إعلان جديد",
        "announcements.messageLabel": "رسالة البث",
        "announcements.messagePlaceholder": "أدخل تفاصيل رسالتك العامة أو الإعلانية هنا...",
        "announcements.targetAudience": "الجمهور المستهدف",
        "announcements.expiryDate": "تاريخ انتهاء الصلاحية (اختياري)",
        "announcements.cancel": "إلغاء",
        "announcements.sendNow": "بث الآن",
        "announcements.historyTitle": "سجل البث الحديث",
        "announcements.total": "الإجمالي {count}",
        "announcements.expires": "ينتهي في: {date}",
        "announcements.confirmDelete": "هل تريد حذف سجل البث هذا؟",
        "announcements.target.all": "الجميع",
        "announcements.target.customer": "العملاء فقط",
        "announcements.target.merchant": "التجار فقط",
        "announcements.success.create": "تم إرسال الإعلان بنجاح",
        "announcements.success.toggle": "تم تحديث حالة الإعلان",
        "announcements.success.delete": "تم حذف الإعلان",
        "announcements.error.create": "فشل إرسال الإعلان",
        "announcements.loading": "جاري تحميل سجل البث...",
        "announcements.noHistory": "لا يوجد سجل للبث حالياً.",
        "announcements.deactivate": "إيقاف",
        "announcements.activate": "تفعيل",

        // Approvals
        "approvals.title": "موافقات التجار",
        "approvals.subtitle": "مراجعة واعتماد طلبات تسجيل التجار وعلاماتهم التجارية الجديدة.",
        "approvals.pendingReview": "قيد المراجعة",
        "approvals.rejectedRequireFix": "مرفوضة / تحتاج تعديل",
        "approvals.refresh": "تحديث",
        "approvals.actions": "الإجراءات",
        "approvals.date": "التاريخ",
        "approvals.reason": "السبب",
        "approvals.brandName": "العلامة التجارية",
        "approvals.merchantInfo": "التاجر",
        "approvals.reject": "رفض طلب",
        "approvals.approve": "موافقة واعتماد",
        "approvals.noPending": "لا توجد طلبات موافقة معلقة.",
        "approvals.noRejected": "لا توجد طلبات مرفوضة حالياً.",
        "approvals.success.approve": "تمت الموافقة على التاجر بنجاح",
        "approvals.success.reject": "تم رفض طلب التاجر بنجاح",
        "approvals.confirmApprove": "هل أنت متأكد من الموافقة على {name}؟",
        "approvals.confirmReject": "ما هو سبب رفض {name}؟",
        "approvals.viewOnMap": "عرض على الخريطة",
        "approvals.noPhone": "لا يوجد هاتف",
        "approvals.noAddress": "لا يوجد عنوان",
        "approvals.initialApplication": "طلب تسجيل مبدئي",
        "approvals.lastRejection": "آخر سبب رفض:",
        "approvals.rejected": "مرفوض",
        "approvals.failedApprove": "فشلت الموافقة على التاجر",
        "approvals.failedReject": "فشل رفض التاجر",
        "approvals.loading": "جاري تحميل الطلبات...",

        // Plans
        "plans.title": "خطط الاشتراك",
        "plans.subtitle": "تهيئة وإعداد خطط الاشتراكات الشهرية والسنوية المتاحة للتجار.",
        "plans.add": "إضافة خطة اشتراك",
        "plans.edit": "تعديل خطة الاشتراك",
        "plans.name": "اسم الخطة",
        "plans.price": "السعر (جنيه)",
        "plans.duration": "المدة",
        "plans.graceDays": "فترة السماح",
        "plans.maxOffers": "العروض المتزامنة",
        "plans.status": "الحالة",
        "plans.actions": "الإجراءات",
        "plans.active": "نشط",
        "plans.inactive": "غير نشط",
        "plans.days": "{days} يوم",
        "plans.confirmDelete": "هل أنت متأكد من رغبتك في حذف خطة الاشتراك هذه؟",
        "plans.success.create": "تم إنشاء خطة الاشتراك بنجاح",
        "plans.success.update": "تم تحديث خطة الاشتراك بنجاح",
        "plans.success.delete": "تم حذف خطة الاشتراك بنجاح",
        "plans.loading": "جاري تحميل الخطط...",
        "plans.form.name": "اسم الخطة",
        "plans.form.price": "السعر بالجنيه المصري",
        "plans.form.duration": "المدة بالأيام",
        "plans.form.grace": "أيام فترة السماح",
        "plans.form.max": "الحد الأقصى للعروض المتزامنة للتاجر",
        "plans.form.isActive": "نشطة ومفعلة للتجار",
        "plans.form.cancel": "إلغاء",
        "plans.form.save": "حفظ الخطة",

        // Subscriptions
        "subs.title": "مراقبة الاشتراكات",
        "subs.subtitle": "متابعة وتفصيل حالات اشتراك كافة التجار وتواريخ انتهائها.",
        "subs.search": "ابحث عن تاجر، بريد إلكتروني، أو علامة تجارية...",
        "subs.daysThreshold": "الحد الأدنى للأيام المتبقية:",
        "subs.filter.all": "الكل",
        "subs.filter.active": "نشط",
        "subs.filter.deactivated": "معطل",
        "subs.filter.expired": "منتهي",
        "subs.filter.ingrace": "في فترة السماح",
        "subs.filter.expiring": "ينتهي قريباً",
        "subs.merchant": "التاجر",
        "subs.brand": "العلامة التجارية",
        "subs.status": "الحالة",
        "subs.termExpiry": "الفترة / الانتهاء",
        "subs.actions": "الإجراءات",
        "subs.loading": "جاري تحميل الاشتراكات...",
        "subs.noSubscriptions": "لم يتم العثور على اشتراكات تجار مطابقة.",
        "subs.daysLeft": "متبقي {days} يوم",
        "subs.daysAgo": "منذ {days} يوم",
        "subs.trial": "تجريبي",
        "subs.graceState": "فترة سماح",
        "subs.deactivated": "معطل",
        "subs.gracePeriod": "فترة سماح",
        "subs.expired": "منتهي",
        "subs.confirmToggle": "هل أنت متأكد من {action} التاجر {name}؟",
        "subs.deactivate": "تعطيل",
        "subs.activate": "تفعيل",
        "subs.deactivateMerchant": "تعطيل التاجر",
        "subs.activateMerchant": "تفعيل التاجر",
        "subs.details.title": "تفاصيل اشتراك التاجر",
        "subs.details.subtitle": "عرض السجل التاريخي، والتحكم اليدوي بتمديد وتغيير اشتراك التاجر.",
        "subs.details.back": "رجوع للاشتراكات",
        "subs.details.info": "معلومات الاشتراك الحالي للتاجر",
        "subs.details.noActive": "لا يوجد اشتراك نشط حالياً لهذا التاجر.",
        "subs.details.plan": "الخطة الحالية",
        "subs.details.startDate": "تاريخ البدء",
        "subs.details.endDate": "تاريخ الانتهاء",
        "subs.details.graceEndDate": "نهاية فترة السماح",
        "subs.details.type": "النوع",
        "subs.details.typeTrial": "فترة تجريبية مجانية",
        "subs.details.typePaid": "اشتراك مدفوع",
        "subs.details.actions": "إجراءات التحكم بالاشتراك",
        "subs.details.extend": "تمديد تاريخ الاشتراك يدوياً",
        "subs.details.extendDays": "أيام التمديد الإضافية",
        "subs.details.extendBtn": "تمديد الاشتراك الآن",
        "subs.details.changePlan": "تغيير خطة الاشتراك يدوياً",
        "subs.details.changeBtn": "تحديث الخطة الآن",
        "subs.details.success.extend": "تم تمديد تاريخ الاشتراك بنجاح",
        "subs.details.success.change": "تم تحديث خطة الاشتراك وتطبيقها بنجاح",
        "subs.details.history": "سجل المعاملات والمدفوعات السابقة",
        "subs.details.noHistory": "لا توجد أي معاملات دفع سابقة مسجلة لهذا التاجر.",
        "subs.details.loadingDetails": "جاري تحميل تفاصيل الاشتراك...",
        "subs.details.merchantNotFound": "التاجر غير موجود.",
        "subs.details.manageCategories": "إدارة الأقسام",
        "subs.details.saveCategories": "حفظ الأقسام",
        "subs.details.graceState": "فترة سماح",
        "subs.details.deactivated": "معطل",
        "subs.details.overview": "نظرة عامة",
        "subs.details.daysRemaining": "الأيام المتبقية",
        "subs.details.graceStatus": "حالة فترة السماح",
        "subs.details.graceEnabled": "مفعلة",
        "subs.details.graceDisabled": "معطلة",
        "subs.details.contactLocation": "الاتصال والموقع",
        "subs.details.phone": "الهاتف",
        "subs.details.address": "العنوان",
        "subs.details.gpsCoordinates": "إحداثيات الموقع",
        "subs.details.openMap": "عرض على الخريطة",
        "subs.details.confirmExtension": "تأكيد التمديد",
        "subs.details.applying": "جاري التطبيق...",
        "subs.details.confirm": "تأكيد",
        "subs.details.dangerZone": "منطقة الخطر",
        "subs.details.forceExpireWarning": "هل أنت متأكد تماماً من رغبتك في إنهاء هذا الاشتراك فوراً؟ سيؤدي ذلك لتعطيل ميزات التاجر النشطة مباشرة.",
        "subs.details.forceExpireWarningEn": "Are you absolutely sure you want to force-expire this subscription? This will immediately disable the merchant's active features.",
        "subs.details.processing": "جاري المعالجة...",
        "subs.details.yesForceExpire": "نعم، قم بالإنهاء فوراً",
        "subs.details.goBack": "تراجع، للوراء",
        "subs.details.forceExpiration": "إنهاء الاشتراك فوراً",
        "subs.details.forceExpirationDesc": "ينهي فوراً فترة الاشتراك الحالية ويحول التاجر إلى حالة 'لا يوجد اشتراك'. استخدم هذا فقط لمخالفات السياسة أو الإلغاءات اليدوية.",
        "subs.details.forceExpireBtn": "إنهاء الاشتراك الآن",
        "subs.details.deactivateMerchant": "تعطيل التاجر",
        "subs.details.activateMerchant": "تفعيل التاجر",
        "subs.details.deactivateDesc": "تعطيل حساب التاجر مؤقتاً. سيؤدي هذا إلى حظر وصوله وتوجيهه وإخفاء علامته التجارية عن العملاء.",
        "subs.details.activateDesc": "استعادة وصول التاجر للحساب. سيتم الحفاظ على حالة اشتراكه الحالية.",
        "subs.details.confirmToggle": "هل أنت متأكد من {action} التاجر {name}؟",
        "subs.details.extensionReason": "سبب التمديد (ملاحظات داخلية)...",
        "subs.details.superAdmin": "مدير عام",

        // Payment Requests
        "requests.title": "طلبات دفع الاشتراكات",
        "requests.subtitle": "مراجعة واعتماد إثباتات دفع الاشتراكات المقدمة يدوياً من التجار.",
        "requests.noRequests": "لا توجد طلبات دفع معلقة للمراجعة.",
        "requests.merchant": "التاجر",
        "requests.plan": "الخطة المطلوبة",
        "requests.payerNumber": "رقم الهاتف / المرسل",
        "requests.date": "تاريخ التقديم",
        "requests.actions": "الإجراءات",
        "requests.status": "الحالة",
        "requests.status.pending": "معلق للمراجعة",
        "requests.status.approved": "تم القبول والاعتماد",
        "requests.status.rejected": "تم الرفض",
        "requests.reviewModal.title": "مراجعة إثبات دفع التاجر",
        "requests.reviewModal.proof": "صورة إثبات الدفع / التحويل المرسلة",
        "requests.reviewModal.noImage": "لم يتم إرسال أي صورة إثبات",
        "requests.reviewModal.notes": "ملاحظات وتوجيهات الإدارة (ستظهر للتاجر في حال الرفض)",
        "requests.reviewModal.reject": "رفض إثبات الدفع",
        "requests.reviewModal.approve": "قبول الإثبات وتفعيل الاشتراك",
        "requests.reviewModal.cancel": "إلغاء",
        "requests.success.approve": "تم قبول طلب الدفع بنجاح وتنشيط الاشتراك للتاجر",
        "requests.success.reject": "تم رفض طلب دفع التاجر بنجاح",
        "requests.review": "مراجعة",
        "requests.rejectReasonPlaceholder": "اشرح سبب رفض إثبات الدفع...",
        "requests.rejectReasonRequired": "يرجى تقديم سبب الرفض",
        "requests.loading": "جاري تحميل الطلبات...",

        // Audit Log
        "audit.title": "سجل التدقيق والمراقبة",
        "audit.subtitle": "تتبع ومراقبة جميع إجراءات الإشراف الإدارية وتغييرات إعدادات النظام.",
        "audit.search": "البحث بالوصف أو اسم المشرف...",
        "audit.allActions": "كل أنواع الإجراءات",
        "audit.actionType": "نوع الإجراء",
        "audit.time.7days": "آخر 7 أيام",
        "audit.time.30days": "آخر 30 يوم",
        "audit.time.90days": "آخر 90 يوم",
        "audit.time.all": "كل الأوقات",
        "audit.headers.dateTime": "تاريخ المعاملة",
        "audit.headers.action": "الإجراء المتخذ",
        "audit.headers.target": "الهدف",
        "audit.headers.admin": "المشرف المسؤول",
        "audit.headers.summary": "تفاصيل وملخص الإجراء",
        "audit.loading": "جاري تحميل السجلات...",
        "audit.noLogs": "لا توجد سجلات تدقيق مطابقة.",
        "audit.total": "الإجمالي: {count} سجل تدقيق",
        "audit.apiNotAvailable": "واجهة سجل التدقيق غير متوفرة",
        "audit.apiRequired": "تتطلب ميزة التدقيق نقطة نهاية مخصصة في الخلفية لجلب إجراءات المسؤول السابقة. يرجى إضافة نقطة النهاية /api/admin/audit لتمكين هذا العرض.",
        "audit.checkAgain": "تحقق مرة أخرى",
        "audit.actions.MerchantApproved": "موافقة التاجر",
        "audit.actions.MerchantRejected": "رفض التاجر",
        "audit.actions.PaymentApproved": "اعتماد الدفع",
        "audit.actions.PaymentRejected": "رفض الدفع",
        "audit.actions.SubscriptionExtend": "تمديد الاشتراك",
        "audit.actions.ForceExpire": "إنهاء الاشتراك",
        "audit.actions.SettingsChanged": "تغيير الإعدادات",
        "audit.actions.PlanCreated": "إنشاء خطة",
        "audit.actions.PlanUpdated": "تحديث الخطة",
        "audit.actions.PlanToggled": "تبديل الخطة",
        "audit.actions.PlanDeleted": "حذف الخطة",
        "audit.actions.Approval": "موافقة",
        "audit.actions.PaymentApprove": "اعتماد الدفع",
        "audit.actions.PaymentReject": "رفض الدفع",
        "audit.actions.SettingsChange": "تغيير الإعدادات",
        "audit.actions.PlanEdit": "تعديل الخطة"
    },
    en: {
        "sidebar.title": "CityOrders Admin",
        "sidebar.dashboard": "Dashboard",
        "sidebar.merchant_approvals": "Merchant Approvals",
        "sidebar.subscription_plans": "Subscription Plans",
        "sidebar.subscriptions": "Subscriptions",
        "sidebar.payment_requests": "Payment Requests",
        "sidebar.audit_log": "Audit Log",
        "sidebar.payment_methods": "Payment Methods",
        "sidebar.categories": "Categories",
        "sidebar.staff": "Staff",
        "sidebar.roles_permissions": "Roles & Permissions",
        "sidebar.promos": "Promo Codes",
        "sidebar.announcements": "Announcements",
        "sidebar.settings": "Settings",
        "sidebar.security": "Security",
        "sidebar.chats": "Chats",
        "sidebar.delivery_network": "Delivery Network",
        "sidebar.delivery_agents": "Pilots & Dues",
        "sidebar.delivery_plans": "Delivery Plans",
        "sidebar.delivery_payment_requests": "Delivery Payment Requests",
        "sidebar.logout": "Log Out",
        // Login
        "login.title": "CityOrders Admin",
        "login.email": "Email Address",
        "login.password": "Password",
        "login.submit": "Sign In",
        "login.loading": "Signing in...",
        "login.accessDenied": "Access denied. Admin account required.",
        "login.success": "Logged in successfully",
        "login.error": "Invalid email or password",
        // Global Settings
        "settings.title": "Global Settings",
        "settings.subtitle": "Configure system-wide parameters for merchants.",
        "settings.free_trial": "Enable Free Trial",
        "settings.free_trial_desc": "Allow new merchants to start a trial without payment.",
        "settings.trial_days": "Free Trial Days",
        "settings.grace_days": "Trial Grace Days",
        "settings.max_offers": "Max Concurrent Offers (Trial)",
        "settings.save": "Save Settings",
        "settings.saving": "Saving...",
        "settings.success": "Settings updated successfully",
        "settings.error": "Failed to update settings",
        "settings.security": "Security",
        "settings.change_password": "Update your admin account password.",
        "settings.current_password": "Current Password",
        "settings.new_password": "New Password",
        "settings.confirm_password": "Confirm New Password",
        "settings.update_password": "Change Password",
        "settings.updating": "Updating...",
        "settings.loading": "Loading settings...",
        "settings.connectionError": "Connection Error",
        "settings.connectionErrorDesc": "Failed to fetch settings from the backend. Please verify that the backend API is running at",
        "settings.settingsUpdated": "Settings updated successfully",
        "settings.settingsUpdateFailed": "Failed to update settings",
        "settings.passwordChanged": "Password changed successfully",
        "settings.passwordChangeFailed": "Failed to change password",
        "settings.passwordMismatch": "New passwords do not match",
        "settings.passwordTooShort": "Password must be at least 6 characters",
        
        // Dashboard
        "dashboard.title": "Dashboard",
        "dashboard.subtitle": "Monitor orders, revenue, and merchants in one place.",
        "dashboard.stats.total_orders": "Total Orders",
        "dashboard.stats.active_orders": "{count} active orders",
        "dashboard.stats.late_orders": "Late Orders",
        "dashboard.stats.late_desc": "Active for more than 30 mins",
        "dashboard.stats.delivered_revenue": "Delivered Revenue",
        "dashboard.stats.today_revenue": "Today: {amount}",
        "dashboard.stats.customers": "Customers",
        "dashboard.stats.new_customers": "{count} new customers in 7 days",
        "dashboard.stats.merchants": "Merchants",
        "dashboard.stats.online_merchants": "{count} online now",
        "dashboard.stats.temp_closed": "Temporarily Closed",
        "dashboard.stats.hidden_merchants": "Hidden from customers",
        "dashboard.stats.pending_approvals": "Pending Approvals",
        "dashboard.stats.pending_payments": "Pending Payments",
        "dashboard.stats.unread_chats": "Unread Messages",
        "dashboard.stats.open_chats": "{count} open chats",
        "dashboard.stats.payment_methods": "Payment Methods",
        "dashboard.stats.free_trial": "Free Trial",
        "dashboard.stats.enabled": "Enabled",
        "dashboard.stats.disabled": "Disabled",
        "dashboard.recent_orders": "Recent Orders",
        "dashboard.recent_orders_desc": "Latest 6 orders",
        "dashboard.no_recent_orders": "No recent orders",
        "dashboard.attention_orders": "Orders Requiring Attention",
        "dashboard.attention_orders_desc": "Oldest active orders",
        "dashboard.no_attention_orders": "No late orders currently",
        "dashboard.system_health": "System Health",
        "dashboard.api_status": "API Status",
        "dashboard.api_online": "Online",
        "dashboard.api_offline": "Offline",
        "dashboard.latency": "Response Time",
        "dashboard.last_checked": "Last Checked",
        "dashboard.retry": "Retry",
        "dashboard.server_error_title": "Connection Failed",
        "dashboard.server_error_desc": "Make sure the backend is running on port 5014 and try again.",
        "dashboard.reconnect": "Reconnect",
        "dashboard.currency": "EGP",
        "dashboard.order_status.pending": "Pending",
        "dashboard.order_status.accepted": "Accepted",
        "dashboard.order_status.preparing": "Preparing",
        "dashboard.order_status.outfordelivery": "Out for Delivery",
        "dashboard.order_status.delivered": "Delivered",
        "dashboard.order_status.cancelled": "Cancelled",
        "dashboard.time.now": "Just now",
        "dashboard.time.minutes_ago": "{count}m ago",
        "dashboard.time.hours_ago": "{count}h ago",
        "dashboard.time.recent": "Recently",

        // Chats
        "chats.title": "Chats",
        "chats.subtitle": "Direct communication between admin and merchants.",
        "chats.start_chat": "Start a conversation",
        "chats.search_placeholder": "Search for a merchant...",
        "chats.loading": "Loading...",
        "chats.no_merchants": "No merchants found.",
        "chats.current_chats": "Current Chats",
        "chats.no_chats": "No chats yet.",
        "chats.loading_messages": "Loading messages...",
        "chats.no_messages_title": "No messages yet",
        "chats.no_messages_desc": "Send the first message to this merchant.",
        "chats.attachment_title": "Attach image",
        "chats.message_placeholder": "Type a message...",
        "chats.send": "Send",
        "chats.select_chat_title": "Select a Chat",
        "chats.select_chat_desc": "Select a merchant or open an existing chat.",
        "chats.read": "Read",
        "chats.sent": "Sent",
        "chats.upload_failed": "Failed to upload image.",

        // Payment Methods
        "payments.title": "Payment Methods",
        "payments.subtitle": "Manage methods merchants use to pay for subscriptions.",
        "payments.add": "Add Method",
        "payments.edit": "Edit Payment Method",
        "payments.displayName": "Display Name",
        "payments.receiver": "Receiver",
        "payments.receiverName": "Receiver Name",
        "payments.receiverNumber": "Receiver Number",
        "payments.instructions": "Instructions",
        "payments.sortOrder": "Sort Order",
        "payments.status": "Status",
        "payments.actions": "Actions",
        "payments.isActive": "Is Active",
        "payments.active": "Active",
        "payments.inactive": "Inactive",
        "payments.confirmDelete": "Are you sure you want to delete this payment method?",
        "payments.success.create": "Payment method created",
        "payments.success.update": "Payment method updated",
        "payments.success.toggle": "Status toggled",
        "payments.success.delete": "Payment method deleted",
        "payments.error.delete": "Failed to delete payment method",
        "payments.loading": "Loading payment methods...",
        "payments.cancel": "Cancel",
        "payments.save": "Save",

        // Categories
        "categories.title": "Master Categories",
        "categories.subtitle": "Manage global product categories and icons.",
        "categories.add": "Add Category",
        "categories.edit": "Edit Category",
        "categories.icon": "Icon",
        "categories.nameSlug": "Name / Slug",
        "categories.name": "Name",
        "categories.slug": "Slug",
        "categories.description": "Description",
        "categories.image": "Image",
        "categories.sortOrder": "Sort Order",
        "categories.status": "Status",
        "categories.actions": "Actions",
        "categories.active": "Active",
        "categories.inactive": "Inactive",
        "categories.search": "Search categories...",
        "categories.showInactive": "Show Inactive",
        "categories.sortByOrder": "Sort by Order",
        "categories.sortByName": "Sort by Name",
        "categories.saveOrder": "Save Order",
        "categories.confirmDelete": "Are you sure you want to delete \"{name}\"? This will also remove its link from any brands.",
        "categories.loading": "Loading categories...",
        "categories.noCategories": "No categories found.",
        "categories.nameRequired": "Name is required",
        "categories.allowedImages": "Allowed: jpg, png, webp. Max 5MB.",
        "categories.cancel": "Cancel",
        "categories.save": "Save",
        "categories.noImg": "No Img",

        // Staff
        "staff.title": "Admin Staff",
        "staff.subtitle": "Manage platform administrators and permissions.",
        "staff.add": "Add Staff Member",
        "staff.search": "Search staff...",
        "staff.total": "Total: {count} Users",
        "staff.assignedRole": "Assigned Role",
        "staff.newStaff": "New Staff Member",
        "staff.fullName": "Full Name",
        "staff.email": "Email Address",
        "staff.password": "Password",
        "staff.adminAccess": "Admin Access",
        "staff.adminAccessDesc": "This user will be granted full unrestricted access to the entire admin panel and dashboard.",
        "staff.createBtn": "Create Staff Member",
        "staff.confirmDelete": "Delete {name}?",
        "staff.success.create": "Admin user created successfully",
        "staff.success.delete": "Admin user deleted",
        "staff.error.create": "Failed to create user",
        "staff.error.delete": "Failed to delete user",
        "staff.loading": "Loading admin users...",
        "staff.superAdmin": "Super Admin",
        "staff.status": "Status",
        "staff.active": "Active",
        "staff.inactive": "Inactive",
        "staff.confirmToggle": "Are you sure you want to toggle the status of {name}?",
        "staff.success.toggleStatus": "Account status toggled successfully",
        "staff.error.toggleStatus": "Failed to update account status",
        "staff.resetPassword": "Reset Password",
        "staff.enterNewPassword": "Enter new password (min 6 characters)",
        "staff.success.resetPassword": "Password reset successfully",
        "staff.error.resetPassword": "Failed to reset password",

        // Roles & Permissions
        "roles.title": "Role Permissions",
        "roles.subtitle": "Configure access control for admin staff",
        "roles.create": "Create Custom Role",
        "roles.systemRoles": "System Roles",
        "roles.customRoles": "Custom Roles",
        "roles.noCustomRoles": "No custom roles created yet.",
        "roles.roleNamePlaceholder": "Role Name (e.g. Support)",
        "roles.systemRoleLabel": "System - Full Access",
        "roles.editBtn": "Edit Permissions",
        "roles.save": "Save",
        "roles.cancel": "Cancel",
        "roles.confirmDelete": "Are you sure you want to delete this role?",
        "roles.systemRoleInfoTitle": "System Role",
        "roles.systemRoleInfoDesc": "System roles have predefined behaviors inside the core application. You cannot modify their individual endpoints here.",
        "roles.endpointsTotal": "{selected} / {total}",
        "roles.selectRolePlaceholder": "Select a role to view or edit permissions",
        "roles.success.create": "Role created successfully",
        "roles.success.update": "Role updated successfully",
        "roles.success.delete": "Role deleted",
        "roles.error.create": "Failed to create role",
        "roles.error.update": "Failed to update role",
        "roles.error.delete": "Failed to delete role",
        "roles.loading": "Loading roles...",

        // Promo Codes
        "promos.title": "Promo Codes",
        "promos.subtitle": "Monitor all promotional codes active across the platform",
        "promos.search": "Search by code or brand name...",
        "promos.noPromos": "No promo codes found",
        "promos.noPromosDesc": "Try adjusting your search or filters.",
        "promos.discount": "Discount",
        "promos.usages": "Usages",
        "promos.minOrder": "Min Order",
        "promos.starts": "Starts:",
        "promos.expires": "Expires:",
        "promos.neverExpires": "Never expires",
        "promos.unlimited": "Unlimited",
        "promos.loading": "Loading promos...",
        "promos.by": "by {brand}",
        "promos.maxDiscount": "(Max {amount} EGP)",
        "promos.status.all": "All",
        "promos.status.active": "Active",
        "promos.status.scheduled": "Scheduled",
        "promos.status.expired": "Expired",
        "promos.status.usedup": "Used Up",
        "promos.status.disabled": "Disabled",

        // Announcements
        "announcements.title": "Global Chat / Announcements",
        "announcements.subtitle": "Broadcast messages and ads to all platform users.",
        "announcements.new": "New Announcement",
        "announcements.messageLabel": "Broadcast Message",
        "announcements.messagePlaceholder": "Enter your global message or advertisement details here...",
        "announcements.targetAudience": "Target Audience",
        "announcements.expiryDate": "Expiry Date (Optional)",
        "announcements.cancel": "Cancel",
        "announcements.sendNow": "Broadcast Now",
        "announcements.historyTitle": "Recent Broadcast History",
        "announcements.total": "{count} Total",
        "announcements.expires": "Expires: {date}",
        "announcements.confirmDelete": "Delete this broadcast log?",
        "announcements.target.all": "Everyone",
        "announcements.target.customer": "Customers Only",
        "announcements.target.merchant": "Merchants Only",
        "announcements.success.create": "Announcement sent successfully",
        "announcements.success.toggle": "Announcement status updated",
        "announcements.success.delete": "Announcement deleted",
        "announcements.error.create": "Failed to send announcement",
        "announcements.loading": "Loading history...",
        "announcements.noHistory": "No broadcast logs found.",
        "announcements.deactivate": "Deactivate",
        "announcements.activate": "Activate",

        // Approvals
        "approvals.title": "Merchant Approvals",
        "approvals.subtitle": "Review and approve new merchant registrations.",
        "approvals.pendingReview": "Pending Review",
        "approvals.rejectedRequireFix": "Rejected / Require Fix",
        "approvals.refresh": "Refresh",
        "approvals.actions": "Actions",
        "approvals.date": "Date",
        "approvals.reason": "Reason",
        "approvals.brandName": "Brand Name",
        "approvals.merchantInfo": "Merchant Info",
        "approvals.reject": "Reject",
        "approvals.approve": "Approve",
        "approvals.noPending": "No pending approvals.",
        "approvals.noRejected": "No rejected approvals.",
        "approvals.success.approve": "Merchant approved successfully",
        "approvals.success.reject": "Merchant request rejected",
        "approvals.confirmApprove": "Are you sure you want to approve {name}?",
        "approvals.confirmReject": "What is the reason for rejecting {name}?",
        "approvals.viewOnMap": "View on Map",
        "approvals.noPhone": "No phone",
        "approvals.noAddress": "No address provided",
        "approvals.initialApplication": "Initial application",
        "approvals.lastRejection": "Last rejection:",
        "approvals.rejected": "Rejected",
        "approvals.failedApprove": "Failed to approve merchant",
        "approvals.failedReject": "Failed to reject merchant",
        "approvals.loading": "Loading approvals...",

        // Plans
        "plans.title": "Subscription Plans",
        "plans.subtitle": "Configure Monthly, Quarterly, and Yearly plans for merchants.",
        "plans.add": "Add Plan",
        "plans.edit": "Edit Subscription Plan",
        "plans.name": "Plan Name",
        "plans.price": "Price (EGP)",
        "plans.duration": "Duration",
        "plans.graceDays": "Grace Days",
        "plans.maxOffers": "Max Offers",
        "plans.status": "Status",
        "plans.actions": "Actions",
        "plans.active": "Active",
        "plans.inactive": "Inactive",
        "plans.days": "{days} days",
        "plans.confirmDelete": "Are you sure you want to delete this plan?",
        "plans.success.create": "Subscription plan created",
        "plans.success.update": "Subscription plan updated",
        "plans.success.delete": "Subscription plan deleted",
        "plans.loading": "Loading plans...",
        "plans.form.name": "Plan Name",
        "plans.form.price": "Price in EGP",
        "plans.form.duration": "Duration in Days",
        "plans.form.grace": "Grace Days",
        "plans.form.max": "Max Concurrent Offers",
        "plans.form.isActive": "Is Active for Merchants",
        "plans.form.cancel": "Cancel",
        "plans.form.save": "Save Plan",

        // Subscriptions
        "subs.title": "Subscriptions Monitoring",
        "subs.subtitle": "Monitor merchant subscription states and upcoming expirations.",
        "subs.search": "Search merchant, email, brand...",
        "subs.daysThreshold": "Days Threshold:",
        "subs.filter.all": "All",
        "subs.filter.active": "Active",
        "subs.filter.deactivated": "Deactivated",
        "subs.filter.expired": "Expired",
        "subs.filter.ingrace": "In Grace",
        "subs.filter.expiring": "Expiring Soon",
        "subs.merchant": "Merchant",
        "subs.brand": "Brand",
        "subs.status": "Status",
        "subs.termExpiry": "Term / Expiry",
        "subs.actions": "Actions",
        "subs.loading": "Loading subscriptions...",
        "subs.noSubscriptions": "No subscriptions found.",
        "subs.daysLeft": "{days} days left",
        "subs.daysAgo": "{days} days ago",
        "subs.trial": "Trial",
        "subs.graceState": "Grace",
        "subs.deactivated": "Deactivated",
        "subs.gracePeriod": "GRACE PERIOD",
        "subs.expired": "EXPIRED",
        "subs.confirmToggle": "Are you sure you want to {action} merchant {name}?",
        "subs.deactivate": "deactivate",
        "subs.activate": "activate",
        "subs.deactivateMerchant": "Deactivate Merchant",
        "subs.activateMerchant": "Reactivate Merchant",
        "subs.details.title": "Merchant Subscription Details",
        "subs.details.subtitle": "View history and manually control merchant subscription.",
        "subs.details.back": "Back to list",
        "subs.details.info": "Current Subscription Info",
        "subs.details.noActive": "No active subscription for this merchant.",
        "subs.details.plan": "Current Plan",
        "subs.details.startDate": "Start Date",
        "subs.details.endDate": "End Date",
        "subs.details.graceEndDate": "Grace End Date",
        "subs.details.type": "Type",
        "subs.details.typeTrial": "Free Trial",
        "subs.details.typePaid": "Paid",
        "subs.details.actions": "Control Actions",
        "subs.details.extend": "Manually Extend Subscription Date",
        "subs.details.extendDays": "Days to Extend",
        "subs.details.extendBtn": "Extend Subscription Now",
        "subs.details.changePlan": "Manually Change Subscription Plan",
        "subs.details.changeBtn": "Update Plan Now",
        "subs.details.success.extend": "Subscription extended successfully",
        "subs.details.success.change": "Subscription plan updated manually",
        "subs.details.history": "Transaction & Payment History",
        "subs.details.noHistory": "No past transactions recorded for this merchant.",
        "subs.details.loadingDetails": "Loading merchant subscription details...",
        "subs.details.merchantNotFound": "Merchant not found.",
        "subs.details.manageCategories": "Manage Categories",
        "subs.details.saveCategories": "Save Categories",
        "subs.details.graceState": "Grace",
        "subs.details.deactivated": "Deactivated",
        "subs.details.overview": "Overview",
        "subs.details.daysRemaining": "Days Remaining",
        "subs.details.graceStatus": "Grace Status",
        "subs.details.graceEnabled": "Enabled",
        "subs.details.graceDisabled": "Disabled",
        "subs.details.contactLocation": "Contact & Location",
        "subs.details.phone": "Phone",
        "subs.details.address": "Address",
        "subs.details.gpsCoordinates": "GPS Coordinates",
        "subs.details.openMap": "Open Map",
        "subs.details.confirmExtension": "Confirm Extension",
        "subs.details.applying": "Applying...",
        "subs.details.confirm": "Confirm",
        "subs.details.dangerZone": "Danger Zone",
        "subs.details.forceExpireWarning": "Are you absolutely sure you want to force-expire this subscription? This will immediately disable the merchant's active features.",
        "subs.details.processing": "Processing...",
        "subs.details.yesForceExpire": "Yes, Force Expire",
        "subs.details.goBack": "Nevermind, go back",
        "subs.details.forceExpiration": "Force Expiration",
        "subs.details.forceExpirationDesc": "Immediately ends the current subscription period and puts the merchant into 'None' state. Use only for policy violations or manual overrides.",
        "subs.details.forceExpireBtn": "Force Expire Now",
        "subs.details.deactivateMerchant": "Deactivate Merchant",
        "subs.details.activateMerchant": "Activate Merchant",
        "subs.details.deactivateDesc": "Temporarily disable the merchant's account. This will block all API access and hide their brand from customers.",
        "subs.details.activateDesc": "Restore the merchant's account access. Their existing subscription status will be maintained.",
        "subs.details.confirmToggle": "Are you sure you want to {action} merchant {name}?",
        "subs.details.extensionReason": "Reason for extension (internal notes)...",
        "subs.details.superAdmin": "Super Admin",

        // Payment Requests
        "requests.title": "Subscription Payment Requests",
        "requests.subtitle": "Review and approve merchant payment proofs.",
        "requests.noRequests": "No pending payment requests.",
        "requests.merchant": "Merchant",
        "requests.plan": "Plan",
        "requests.payerNumber": "Payer Number",
        "requests.date": "Date",
        "requests.actions": "Actions",
        "requests.status": "Status",
        "requests.status.pending": "Pending",
        "requests.status.approved": "Approved",
        "requests.status.rejected": "Rejected",
        "requests.reviewModal.title": "Review Payment Proof",
        "requests.reviewModal.proof": "Payment Proof Image",
        "requests.reviewModal.noImage": "No image provided",
        "requests.reviewModal.notes": "Admin Notes (visible to merchant if rejected)",
        "requests.reviewModal.reject": "Reject Request",
        "requests.reviewModal.approve": "Approve & Activate",
        "requests.reviewModal.cancel": "Cancel",
        "requests.success.approve": "Payment approved and subscription activated",
        "requests.success.reject": "Payment request rejected",
        "requests.loading": "Loading requests...",
        "requests.review": "Review",
        "requests.rejectReasonPlaceholder": "Explain why the proof was rejected...",
        "requests.rejectReasonRequired": "Please provide a reason for rejection",

        // Audit Log
        "audit.title": "Audit Log",
        "audit.subtitle": "Track all administrative actions and system changes.",
        "audit.search": "Filter by description or target...",
        "audit.allActions": "All Actions",
        "audit.actionType": "Action Type",
        "audit.time.7days": "Last 7 Days",
        "audit.time.30days": "Last 30 Days",
        "audit.time.90days": "Last 90 Days",
        "audit.time.all": "All Time",
        "audit.headers.dateTime": "Date / Time",
        "audit.headers.action": "Action",
        "audit.headers.target": "Target",
        "audit.headers.admin": "Administrator",
        "audit.headers.summary": "Summary",
        "audit.loading": "Loading audit logs...",
        "audit.noLogs": "No audit logs found.",
        "audit.total": "Total: {count} Logs",
        "audit.apiNotAvailable": "Audit API Not Available",
        "audit.apiRequired": "The auditing feature requires a specialized backend endpoint to fetch historical admin actions. Please add the /api/admin/audit endpoint to enable this view.",
        "audit.checkAgain": "Check Again",
        "audit.actions.MerchantApproved": "Merchant Approval",
        "audit.actions.MerchantRejected": "Merchant Rejection",
        "audit.actions.PaymentApproved": "Payment Approval",
        "audit.actions.PaymentRejected": "Payment Rejection",
        "audit.actions.SubscriptionExtend": "Subscription Extend",
        "audit.actions.ForceExpire": "Force Expire",
        "audit.actions.SettingsChanged": "Settings Change",
        "audit.actions.PlanCreated": "Plan Created",
        "audit.actions.PlanUpdated": "Plan Updated",
        "audit.actions.PlanToggled": "Plan Toggled",
        "audit.actions.PlanDeleted": "Plan Deleted",
        "audit.actions.Approval": "Approval",
        "audit.actions.PaymentApprove": "Payment Approval",
        "audit.actions.PaymentReject": "Payment Rejection",
        "audit.actions.SettingsChange": "Settings Change",
        "audit.actions.PlanEdit": "Plan Edit"
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        return (localStorage.getItem('adminLanguage') as Language) || 'ar';
    });

    useEffect(() => {
        localStorage.setItem('adminLanguage', language);
        // Apply RTL/LTR to document root
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        const dict = translations[language];
        return (dict as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useTranslation must be used within LanguageProvider');
    return context;
};
